### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by watson** [adventure-js/arcticjs.club#10]
## Monday

Arrival day - Random hacks of :snowflake: 
## Tuesday
- [x] Morning: Location scouting and talking to the Sysselmannen
- [x] Evening: Show and tell (show off what you've worked on today)
## Wednesday
- [x] **ArcticJS**
  - **Important:** Bring cash for coffee
  - **Location:** [The Northernmost Church on Planet Earth](https://goo.gl/maps/Fu7RWh3SSs62)
  - **Timezone:** CET
  - 12:00 - Venue opens
  - 12:25 - Welcome
  - 12:30 - "Security vulnerabilities in printers" by @watson
  - 13:00 - "git yolo" by @RichardLitt
  - 13:30 - "Hacking poker" by @nealwu
  - 14:00 - "Collaborative p2p text editing" by @noffle 
  - 14:30 - "God has abandoned type overloading and so should humans" by @mafintosh
  - 15:00 - "Using ancient browser APIs for fun (and profit?)" by @feross
  - 15:30 - "Learnings of using Node.js and the Open Source ways for Academic Research and Higher Education" by @diasdavid 
  - 16:00 - Untitled by @lpi
  - 16:30 - "The impending mesh web" by @whyrusleeping 
- [x] ~~Show and tell (show off what you've worked on today)~~ _\- we'll most like just go out to eat and drink after the conference_
- [x] Whiskey Wednesday
## Thursday
- [x] 12:00 Ice-cave Thursday
- [x] ~~Show and tell (show off what you've worked on today)~~ _\- we've most likely not achieved much coding this day_
## Friday

Travel day

**Comment by ralphtheninja** [comment]
@copernicus-mogley Would be awesome if you could post the live stream urls here.

**Comment by watson** [comment]
This is our official schedule - We'll discuss stuff on IRC and IRL and add it here :smiley: 

@mafintosh, @feross, @jhiesey, @nealwu, @lpi, @whyrusleeping, @diasdavid, @despairblue, @dcposch, @RichardLitt, @noffle, @copernicus-mogley

**Comment by copernicus-mogley** [comment]
Livestream link for "Security Vulnerabilities in Printers" by @watson
https://www.youtube.com/watch?v=0v12Nu5UDFw

**Comment by ralphtheninja** [comment]
@watson At what time do you start these sessions/talks?

**Comment by copernicus-mogley** [comment]
@ralphtheninja 2pm Central European Time (probably)
Here's the livestream link for talk by @feross and @mafintosh ... https://www.youtube.com/watch?v=ONEdNNbLBd8

**Comment by copernicus-mogley** [comment]
The schedule is still in the works. We're making changes now. Keep an eye on this issue. @ralphtheninja

**Comment by lpi** [comment]
Arctic Tapas: http://arctictapas.com/what-do-you-get/

2.5 hour bus tour of the island. Includes 4 course meal. Anyone interested in this? 795 NOK but if we use up the entire bus we can probably negotiate a discount.

**Comment by RichardLitt** [comment]
I'm not sure. I think it'd be too dark to actually be interesting this time of year.

**Comment by hackergrrl** [comment]
@lpi: it's a shame it runs at 1800h when it's already "dark" out. It might've worked if it was closer to 1100h?

**Comment by RichardLitt** [comment]
I think it is for the summer. Note that the birds it mentions; all of the migratory birds are gone this season.

**Comment by copernicus-mogley** [comment]
Livestream links:
@watson == https://www.youtube.com/watch?v=0v12Nu5UDFw
@RichardLitt == https://www.youtube.com/watch?v=_KY9ltbdoK4
@noffle == https://www.youtube.com/watch?v=RXq-WVn4DCI
@nealwu== https://www.youtube.com/watch?v=cCBuLmchhbk
@feross == https://www.youtube.com/watch?v=ONEdNNbLBd8
@lpi == https://www.youtube.com/watch?v=5F0RGv5eqbU
@diasdavid == https://www.youtube.com/watch?v=L_GW3G_6ZmU
@mafintosh == https://www.youtube.com/watch?v=Qj4zbnI-4Jw
@whyrusleeping == https://www.youtube.com/watch?v=fVSu_t0CsWA
Lightning Talks + Open Discussion == https://www.youtube.com/watch?v=EH4hb9R_cBE

**Comment by RichardLitt** [comment]
Thanks @copernicus-mogley!

**Comment by hackergrrl** [comment]
Could I get on the schedule for a short talk?

**Comment by RichardLitt** [comment]
Add your talks to the [talks](https://github.com/watson/arcticjs.club/tree/gh-pages/talks) folder.
