### ISSUE TITLE
Sysselmannen

### ISSUE THREAD

**Issue by RichardLitt** [adventure-js/arcticjs.club#11]
So, I think we should get a talk by the governor, because it would be awesome. 

Current plan: Go to UNIS tomorrow and see if we can get a room for Wednesday. Then, we'll email the Sysselmann and see if he wants to talk to us about Svalbard for twenty minutes for the first JS conf north of the arctic circle. 

**Three +1s and I will go through with this plan.**

**Comment by mafintosh** [comment]
:+1:

**Comment by fbaiodias** [comment]
:+1:

**Comment by yangwao** [comment]
:+1:

**Comment by RichardLitt** [comment]
Great. Doing this tomorrow morning, then, after the morning dip in the ocean at 9am.

**Comment by despairblue** [comment]
:+1:

**Comment by RichardLitt** [comment]
OK! So, I went to a few places this morning. UNIS is totally blocked out. Svalbard Hotel is using their conference room for storage. I couldn't find the Spitsbergen hotel, and I'm not sure why. The Radisson is under repairs, I think. I haven't checked at the cultural center. 

But the Tourist office does have a room, and it is at a guest house around 2km up the valley. We can have the room; it is big enough for 10~ people, and I've asked to book it from 12 to 4pm tomorrow (Wednesday). The cost is 250 KOR, or we can help the person who booked it with the website for the tourism board, because she doesn't know how to update it (specifically, she wants to add a table). 

What do you think? I think let's do it, because it'll also be nice to walk a bit.

**Comment by whyrusleeping** [comment]
:+1:

**Comment by daviddias** [comment]
here you go, three plus ones :) :+1: :+1: :+1:

**Comment by RichardLitt** [comment]
OK. So, Kulturhouse has no available rooms. Thanks, @watson. We went to the Sysselmann's office; we needed to submit a request, in writing, a month before. Seeing that, I asked if there was a cultural advisor; they said there isn't. Svalbard doesn't do that, apparently. The local government for the city doesn't have any rooms available, either; we didn't ask about having someone say hi, but I'm not sure that we really want that. So, it looks like ArcticJS will have no people from Svalbard, unless @whyrusleeping can get our AirBnB host. 

There are now three options for hosting a room for the larger talks:
- [ ] Kroa or a cafe. I don't like this plan, because it is annoying to everyone else there. 
- [ ] The tourist board. I need to tell them. Price: 250KR or some help setting up their website. I don't think this would be too hard. 
- [ ] Our AirBnB for an hour or two, as it isn't the biggest, but could fit us all for a tiny bit without a serious problem. 

The other thing I failed to mention earlier is that the Tourist thing is 2km up the valley, but also that the woman was worried about us taking down their network. Given that every time we sit at a cafe and @diasdavid opens his laptop the internet slows down significantly, it may not be possible for us to use this network. I suggest that if we do this, we don't have internet for the hour of talks except for the people giving the talk. I don't think this is too unreasonable, as it is what every other industry does anyway. So, let's do that. 

Now, why doesn't GitHub have a polling option? 

Please let me know in the next 30 minutes so that I can tell the tourist board if we don't want to use our AirBnB. 

Added benefit of our airbnb: coffee courtesy of @whyrusleeping, beer, and a stove on which we can have a local cookout before taking a dip in the ocean at 9pm.

**Comment by mafintosh** [comment]
:+1: tourist. if a speaker needs some internet i can provide roaming

**Comment by ralphtheninja** [comment]
> Given that every time we sit at a cafe and @diasdavid opens his laptop the internet slows down significantly

Hahahahaha

**Comment by RichardLitt** [comment]
Another option may be the church. @watson is going to go ask, because that would actually be kind of cool. It is the most northernmost church in the world, and God uses semicolons. 

> Genesis 1:27: So God created mankind in his own image, in the image of God he created them; male and female he created them.

**Comment by mafintosh** [comment]
we booked the church for tomorrow. we have it from noon to around 16. they have a projector and coffee (bring cash to buy coffee)

**Comment by mafintosh** [comment]
oh and they have wifi as well

**Comment by RichardLitt** [comment]
Awesome. That is super cool. So, closing this issue.

**Comment by watson** [comment]
Yeah, as @mafintosh said I think they kind of hinted that we should buy coffee from them as a way of "paying" for borrowing the church - so it would be a nice gesture if we bought coffee at the church :smiley:

**Comment by ralphtheninja** [comment]
> we booked the church for tomorrow. we have it from noon to around 16. they have a projector and coffee (bring cash to buy coffee)

This is getting more epic by the hour!
