### ISSUE TITLE
actual sounds from svalbard

### ISSUE THREAD

**Issue by whyrusleeping** [adventure-js/arcticjs.club#13]
Would be cool if the background audio was really audio from svalbard:

http://mars.i.ipfs.io:8080/ipfs/QmXgXkMGHwKvSULKXJLgjU7K4KS7jhsy47jEUxy2WQ3A4V/water.mp3

Thats some waves i recorded last night. theres a bit of wind sound (subtly), so i'm going to do another recording tonight when i get a chance.

**Comment by mafintosh** [comment]
just change this line to your link, https://github.com/watson/arcticjs.club/blob/gh-pages/index.html#L204

**Comment by RichardLitt** [comment]
@mafintosh See PR.

**Comment by RichardLitt** [comment]
Changed! :D

**Comment by mafintosh** [comment]
sweet
