### ISSUE TITLE
Best meetup/conference ever!

### ISSUE THREAD

**Issue by joshmanders** [adventure-js/arcticjs.club#15]
Guys seriously, between the location, down to the name, to how fun you guys looked like you were having on the live streams, I hope this continues on next year and the years after that. I'm definitely down to going to any future ones.

I've been working on a small contracting and product company on the side of my primary job, and I had chosen the name Arcticbyte before this showed up, and I'd definitely be down to sponsoring the next one. 

Sincerely Me & Grylls the Polar Bear

![](http://i.imgur.com/YxVsip6.jpg)

**Comment by RichardLitt** [comment]
! That's awesome! We are definitely planning a next one. :) Hope to see you soon in person.

**Comment by watson** [comment]
Thank you @joshmanders :smiley: We're really happy and actually still a little baffled that this crazy idea we had only a few weeks ago spread to so many awesome people. A lot couldn't come unfortunately, but seeing you guys enjoying the live stream makes it even more worth it - there will most definitely be a next one.

**Comment by whyrusleeping** [comment]
:+1:

**Comment by feross** [comment]
:+1: :+1: :+1:
