### ISSUE TITLE
Summer edition

### ISSUE THREAD

**Issue by mafintosh** [adventure-js/arcticjs.club#17]
We need to go somewhere with 24 hour light in the summer. Let's make this the idea / planning thread.

**Comment by watson** [comment]
I'm going to Nuuk, Greenland this summer as I have family there. I'm not sure if it's far enough north to have 24 hour sunlight, but we can probably look that up somewhere.

**Comment by RichardLitt** [comment]
So, we have a few options. There is a list of [polar settlements](https://en.wikipedia.org/wiki/Northernmost_cities_and_towns) that is useful. We've already been to the main one -- No.3 is Longyearben -- and I don't think that going to Alert or Ny-Ålesund is really possible. But there are other options. 

![](https://upload.wikimedia.org/wikipedia/commons/3/31/Arctic_circle.svg)
- [Qaanaaq, Greenland](https://en.wikipedia.org/wiki/Qaanaaq). Population: 656. Has internet at [Hotel Qaanaaq](http://www.hotelqaanaaq.dk/hotele.html). Limited online presence. Fixed-wing flights though, which is needed.
- [Resolute, Canada](https://en.wikipedia.org/wiki/Resolute,_Nunavut). Population: 229. Three hotels, has internet. 
- [Barrow, Alaska](https://en.wikipedia.org/wiki/Barrow,_Alaska). Population: 4k. Lots of tourists, roughly twice the size of Longyearben. Internet, passenger flights from Anchorage and Fairbanks. Seems like a very likely option, and right next to the highest point in the US. 
- [Hammerfest, Norway](https://en.wikipedia.org/wiki/Hammerfest_%28town%29). Pop: 7500. Probably easy to get to from Alta, maybe from Oslo. Very pretty.
- [Alta, Norway](https://en.wikipedia.org/wiki/Alta_%28town%29). Pop: 15,000. A city, flights from Oslo, and we can take a car and go to the top of Norway, I think. This seems like a smaller option than Tromsø, but still a good one. 
- [Tromsø, Norway](https://en.wikipedia.org/wiki/Troms%C3%B8). Pop: 72k. We've already been here, we just didn't get off the plane. I think this would have the most stuff to do that doesn't involve drinking or wandering around the tundra. Not quite as romantically adventurous, though!

On a similar note, [Skagway](https://en.wikipedia.org/wiki/Skagway,_Alaska) has sun from [2:30am to 10:00pm](http://www.alaska.org/weather/daylight-hours/skagway/july) in July, and I'm hoping to host a JS conf there with @simonv3 at some point this summer, anyway. Nuuk is below the arctic circle, @watson, so it doesn't get 24 hour sunlight. The same can be said for Reykjavik. But those are also good options.

**Comment by RichardLitt** [comment]
Oh, and I am hoping to go to [Cambridge Bay](https://en.wikipedia.org/wiki/Cambridge_Bay), anyway! This might be the best option. There are several hotels, and good internet. There's a daily flight from Yellowknife, which should be easy-ish to get to. If we do this one, we can also take a few days and go on a nice trek. :D

**Comment by whyrusleeping** [comment]
> I think this would have the most stuff to do that doesn't involve drinking or wandering around the tundra.

People do other things?

**Comment by yangwao** [comment]
count me for **FaroeJS**!

**Comment by despairblue** [comment]
For anything in the US please consider that it can take a while to get a visa, so 2 weeks in advance would most certainly not work for a lot of us. So things like Alaska should be set in stone quite early.

**Comment by mafintosh** [comment]
@despairblue thats why i opened this issue already :)

**Comment by despairblue** [comment]
perfect :smile:

**Comment by mafintosh** [comment]
@rusintez is from [Yakutsk](https://www.google.dk/maps/place/Yakutsk,+Sakha+Republic,+Russia/@62.033008,129.5661102,11z/data=!3m1!4b1!4m2!3m1!1s0x5bf63939a0d2c47d:0x69b4c4b35cafa2fb) which is one of the coldest places on earth. would be fun to do a meetup there as well

**Comment by simonv3** [comment]
I'll be moving to Skagway in March, so you'd have someone there beforehand. 

I would +1 Barrow, but it's not "near" Denali, though I guess you could fly over it if you got on a specific flight.

Having spent a summer in Denali, which isn't "high enough" for 24 hour sunlight, (there's 1 hour between sunrise and sunset: 1 - 2 AM), it's still largely twilight, so pretty light. Just to give you an idea - we were playing outdoor sports without a problem. Denali is also cool because it's pretty accessible wilderness that you can go hike and camp in and avoid bears and hang out with caribou and run away from moose. The Internet is pretty good, but it is pretty touristy at the entrance of the park. [Gates of the Arctic](https://en.wikipedia.org/wiki/Gates_of_the_Arctic_Wilderness)?

Offline First JS?

**Comment by mafintosh** [comment]
@simonv3 whooooa that looks amazing

**Comment by joshmanders** [comment]
Alaska sounds amazing. We can get @jfhbrook to come, he's an Alaskan native.

**Comment by yangwao** [comment]
OfflineFirstJS sounds good!

**Comment by feross** [comment]
Really like the idea of going someplace that's completely offline.

**Comment by RichardLitt** [comment]
So, there's another option. It turns out that Iceland has an island called [Grímsey](https://en.wikipedia.org/wiki/Gr%C3%ADmsey) which bisects the Arctic circle. You can get there by plane from Reykjavík, and there are a few people on the island, as well as a church we could use.

**Comment by rusintez** [comment]
my friend is a photographer from tiksi, check some of her shots made there: http://www.evgeniaarbugaeva.com/stories/---tiksi/01/

**Comment by jfhbrook** [comment]
> he's an Alaskan native.

FTR not native, actually white as fuck.

**Comment by joshmanders** [comment]
Not native Alaskan as in an eskimo, but you're from there. :P

**Comment by yangwao** [comment]
for Offline1stJS we should invite @janl or @espy someone from hood.ie team as well. And list it at https://github.com/offlinefirst/events/ yay! :dancer:

**Comment by RichardLitt** [comment]
How do you guys think we should vote on the next edition? I'm afraid that this issue will see falloff in participation as people forget about it.

**Comment by despairblue** [comment]
Majority? Simply by comment? I'd be for Longyearbyen again or Faroe (or something in Russia). Going to Alaska is quite expensive when I checked. Though combining it with a stay in the states may make it more affordable.

**Comment by yangwao** [comment]
Faroe combined with some local hiking?

Btw I'm cooking Offline1st sticker, I'll put it in hexab.in whenever it
will be done.

**Comment by hackergrrl** [comment]
Yes! I was talking to @RichardLitt at ArcticJS about taking an offline-js approach: no internet -- only our own local networks -- as a means of creating a stimulating environment for building offline-first web apps, multicast dns, bluetooth, and p2p mad science.

**Comment by daviddias** [comment]
I like that idea :) btw, that event can be a follow up of both ArcticJS and Battlemesh (happening in May this year) and we would literally hook up our shacks with a mesh network built on the fly :)

**Comment by yangwao** [comment]
I can bring some boards from [hardkernel.com](http://www.hardkernel.com/main/main.php) (XU4, C1+) for IPFS nodes :dancers:

**Comment by hackergrrl** [comment]
Maybe we can build and rig up a couple of [these](http://koruza.net) for AirBNB<->AirBNB connectivity.

**Comment by whyrusleeping** [comment]
@noffle those look amazing

**Comment by feross** [comment]
@noffle Wow, really cool. If we decide to start a permanent settlement in the abandoned city across from Longyearbyen, maybe we could use more powerful versions of these to get internet connectivity over there.

**Comment by hackergrrl** [comment]
@feross definitely. These let us sidestep all of the RF band regulation we'd have to otherwise worry about.

**Comment by bcomnes** [comment]
Are snowflurries transparent to infrared?

**Comment by hackergrrl** [comment]
@bcomnes: good question. Its github repo doesn't explicitly mention it, though the paper [Optical Properties of Snow](http://www.atmos.washington.edu/~sgw/PAPERS/1982_RGSP.pdf) claims snow is ~99% invisible to infrared.

**Comment by yangwao** [comment]
bump, any suggestion for dates yet?
just missed tickets to JSConf Iceland (25-26.8). Is anyone going there?

**Comment by yangwao** [comment]
Also, what about conference at [Yamal](https://en.wikipedia.org/wiki/Yamal_%28icebreaker%29)?

**Comment by watson** [comment]
It's all hush hush, but check out issue #21 for the next ArcticJS 😄
