### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by mafintosh** [adventure-js/arcticjs.club#18]
Could we post links to all the great photos taken at the conference here?

**Comment by feross** [comment]
Here's some that other folks posted: http://ipfs.alexandria.media/ipfs/QmeWz9YZEeNFXQhHg4PnR5ZiNr5isttgi5n1tc1eD5EfGU/content/index.html

**Comment by feross** [comment]
Everyone, post your photos! :)

**Comment by copernicus-mogley** [comment]
Here's the other set of photos that I posted: http://ipfs.alexandria.media/ipfs/QmSnEvxUSSJeMfmA4dqkhti9tJRY9f1CzuLrYVLN1DrFVm/content/index.html

**Comment by copernicus-mogley** [comment]
If anyone wants any of these in high-res and/or CR2, let me know and I'll hook you up. Feel free to share/use however you wish.

**Comment by feross** [comment]
Oh, didn't know that IPFS / Alexandria was not using the hi-res versions. Can you link me to the hi-res ones?

**Comment by copernicus-mogley** [comment]
Sure. The galleries that I usually post are cropped jpegs with some html for easy viewing. I will put the CR2 photos from these two galleries on IPFS and post the link. It might take a few days because of travel and internet connections.

**Comment by watson** [comment]
https://www.dropbox.com/sc/md86rughf5mqkc8/AADxf8x-wz1CB7KgASCIQ4xOa
- Sent from my iPhone

**Comment by hackergrrl** [comment]
Here are mine: a mish-mash of the northern lights, Longyearbyen, the glorious outdoors... and mostly-naked men.

http://tmp.stephenwhitmore.com/arcticjs/

**Comment by RichardLitt** [comment]
https://www.dropbox.com/sh/exxgt3v1m99j9eo/AABDvsvamNSH9kcx_zVlNszha?dl=0

**Comment by RichardLitt** [comment]
How should we best centralize these? Ought we to load them into this repo, maybe?

**Comment by whyrusleeping** [comment]
@diasdavid where are those pictures I took????????

**Comment by feross** [comment]
Will post my pics soon - though I don't have too many. Thanks to all who have shared so far!

**Comment by daviddias** [comment]
I've collected all the pics and videos already posted and added mine as well. You can access it through the gateways, but it would be really nice if you load through you local daemon, so that download speeds get faster to everyone :)

[QmRXwyrSgkMvGkbHmSJ9hwg8RQyMv99DSA9dEHMCToMVxc pics](http://v04x.ipfs.io/ipfs/QmRXwyrSgkMvGkbHmSJ9hwg8RQyMv99DSA9dEHMCToMVxc)
[QmQCKWLQccT1NfaXwfAXYzqgaxqRytJCDWTyPoteNvN1Fc video](http://v04x.ipfs.io/ipfs/QmQCKWLQccT1NfaXwfAXYzqgaxqRytJCDWTyPoteNvN1Fc)

**Comment by bcomnes** [comment]
Thanks for that @diasdavid !
