### ISSUE TITLE
Move to SSL?

### ISSUE THREAD

**Issue by RichardLitt** [adventure-js/arcticjs.club#20]
Should I move this to Netlify and make it https?

**Comment by bcomnes** [comment]
I did this with all of my sites recently.  Definately recommend it for the https and [custom toolchains](https://github.com/bcomnes/bret.io/blob/master/package.json#L6-L22).

**Comment by watson** [comment]
@RichardLitt damn, thought github supported that on custom domains. Apparently not. I don't know Netlify. All I want is that it's dead simple to publish changes.

**Comment by RichardLitt** [comment]
@watson Netlify enables that. It's a super simple process, and you still push to GitHub for it to publish.

**Comment by watson** [comment]
cool, let's do that :)

**Comment by RichardLitt** [comment]
Sweet. I can't set the DNS; do you want to? https://www.netlify.com/docs/custom-domains/

**Comment by watson** [comment]
@RichardLitt have you set up everything so that when the DNS changes it will work as now?

**Comment by RichardLitt** [comment]
Seems to work. http://58a9eee2c4d9cc1b9cd8d870.arcticjs.netlify.com/2017. Might break on https; let me know when you change over, and I can see if I can fix it // test it easily.

**Comment by watson** [comment]
@RichardLitt It doesn't work. I'm getting this error:
<img width="434" alt="screen shot 2017-02-19 at 22 03 25" src="https://cloud.githubusercontent.com/assets/10602/23106533/5239384a-f6ef-11e6-8eaa-47e144f0d1a7.png">

I've changed it back to github for the time being.

I did this:

> Recommended: Use a DNS provider that supports ANAME or ALIAS records for apex domains, and alias your naked domain to www.netlify.com.

**Comment by RichardLitt** [comment]
Hmm. Did you dig the site? 

My settings that worked: 
<img width="827" alt="screenshot 2017-02-19 18 37 39" src="https://cloud.githubusercontent.com/assets/910753/23107839/87303f48-f6d2-11e6-9a00-92d348e44ae0.png">

**Comment by watson** [comment]
```
$ dig arcticjs.club

; <<>> DiG 9.8.3-P1 <<>> arcticjs.club
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38555
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;arcticjs.club.			IN	A

;; ANSWER SECTION:
arcticjs.club.		40	IN	A	54.93.54.1

;; Query time: 42 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Feb 19 22:01:53 2017
;; MSG SIZE  rcvd: 47
```

**Comment by RichardLitt** [comment]
Yep, that's how it is now. Let's try to do this live over IRC.

**Comment by watson** [comment]
Works 😃:shipit:

**Comment by RichardLitt** [comment]
Woot.
