### ISSUE TITLE
Subarctic train journey

### ISSUE THREAD

**Issue by RichardLitt** [adventure-js/arcticjs.club#25]
Hey 👋. I just posted a plan for a train journey in Québec, Canada I am planning in the next few weeks over [here](https://github.com/adventure-js/about/issues/6), if anyone is interested. Posting here as this repo as more watchers. :)

**Comment by whyrusleeping** [comment]
oooooh, I dont think I can make it, but that sounds amazing... Keep us posted on more specific dates :)

**Comment by RichardLitt** [comment]
I did this!
