### ISSUE TITLE
Stickers!

### ISSUE THREAD

**Issue by feross** [adventure-js/arcticjs.club#3]
Inspired by this sign:

![polar-bear-warning-longyearbyen](https://cloud.githubusercontent.com/assets/121766/12208627/40a409bc-b64e-11e5-9050-397149f223ea.jpg)

We came up with this sticker:

![arcticjs](https://cloud.githubusercontent.com/assets/121766/12208635/4669514a-b64e-11e5-986a-6426929f9e33.png)

We're going to try our best to get them printed in time for the conference, but it's going to be tricky!

**Comment by watson** [comment]
This is the best thing ever :santa: :tada: :+1: :sunglasses:

**Comment by yangwao** [comment]
want, three pcs! :)

**Comment by despairblue** [comment]
I have to buy a new computer for that sticker!

**Comment by RichardLitt** [comment]
How are these going?

**Comment by feross** [comment]
It's too late to get StickerMule to make them so @watson is going to visit www.vesterkopi.dk/en/ tomorrow and try to get some made ASAP.

**Comment by watson** [comment]
@feross thanks for reminding me :smiley:

**Comment by RichardLitt** [comment]
Nice!

**Comment by watson** [comment]
Just put in a quotation request - they need to have a board meeting first before they can give me an estimate :tired_face::gun: - I guess we'll know in a few days...

![img_8349](https://cloud.githubusercontent.com/assets/10602/12230732/91545a6e-b852-11e5-849f-d43da454bb03.jpg)

**Comment by RichardLitt** [comment]
We can send these out afterwards. As long as they do exist at some point.

**Comment by watson** [comment]
Spreadsheet with prices from Vesterkopi (they can print them before the weekend): https://docs.google.com/spreadsheets/d/1XHR-YEDN7LukMCf8Z_g9QLPwk6jgl5AGuOTDdOMuhNI/edit?usp=sharing

I think the prices are ok. Buying 50 from stickermule with shipping to Denmark is $100, so this is a little bit more expensive, but it's within the margins of Danish taxes and labor + they do it before the weekend which stickermule cannot.

/cc @feross @mafintosh

**Comment by RichardLitt** [comment]
That seems fine to me.

**Comment by mafintosh** [comment]
:+1: from me

**Comment by despairblue** [comment]
So that's like 3-4 stickers per person. Is that enough? :smile:

**Comment by watson** [comment]
The stickers are ready for pickup on Friday at noon :smile:

**Comment by RichardLitt** [comment]
Woot!

**Comment by feross** [comment]
Nice!

**Comment by watson** [comment]
@mafintosh The stickers are ready! Could you pick them up if you're in town?

**Comment by watson** [comment]
:tada: I think it's time to close this issue :wink: 

![img_8351 jpg](https://cloud.githubusercontent.com/assets/10602/12372089/4ded8df2-bc4b-11e5-9b17-84a4a068055d.jpeg)

See y'all soon!

**Comment by RichardLitt** [comment]
:bear:
