### ISSUE TITLE
Polar bear safety

### ISSUE THREAD

**Issue by hackergrrl** [adventure-js/arcticjs.club#4]
Apparently polar bears are a serious danger in Svalbard. If you're attending, it might be worth doing some reading: http://kho.unis.no/doc/Polar_bears_Svalbard.pdf

**Comment by RichardLitt** [comment]
:bear: :+1:

**Comment by feross** [comment]
Yes, this is not a joke: https://en.wikipedia.org/wiki/2011_Svalbard_polar_bear_attack

However, if you remain in the main settlement area, polar bears shouldn't be an active threat.

**Comment by feross** [comment]
The stay safe section of Wikitravel is worth reading: http://wikitravel.org/en/Svalbard#Stay_safe
