### ISSUE TITLE
Shelter

### ISSUE THREAD

**Issue by watson** [adventure-js/arcticjs.club#5]
:hotel: Everybody is responsible to their own accommodation, but if you want to save money use this issue to coordinate with others to share a place or a room.

**If you're looking for a roommate, post a comment on this issue.**

If you want to book a place, try these sites:
- [Airbnb](https://www.airbnb.com)
- [Couchsurfing](https://www.couchsurfing.com)
- [Hotels.com](https://www.hotels.com)

For cheap accommodation try the [Gjestehuset 102 hostel](http://www.gjestehuset102.no).

**Comment by terinjokes** [comment]
I might be up for it if I can split accommodation with someone.

**Comment by grafana-dee** [comment]
More hotels here: http://www.tripadvisor.com/Hotels-g503715-Longyearbyen_Spitsbergen_Svalbard-Hotels.html

There's even a Radisson:
https://www.radissonblu.com/en/hotel-spitsbergen

And this one has spaces:
http://www.scandichotels.com/Hotels/Norway/Longyearbyen/Spitsbergen-Hotel/

**Comment by terinjokes** [comment]
@buro9 "Hotel is undergoing renovations and is closed until Q1 2016". It reopens on the 22nd.

---

Scandic Partner Spitsbergen Hotel is going for $166/night right now.

**Comment by despairblue** [comment]
Anyone up for sharing a room for four at http://www.gjestehuset102.no/phone/rooms---rates.html? Would be with me and my girlfriend (she's just there for museums, studying for her exams and wrestling polar bears. Not a Programmer yet, though I'm working on that part :D). 

So there is room left for 2 people.
Should be around 33 € or 36 $ per person per night. Breakfast included.

**Comment by despairblue** [comment]
Ok booked a room for two here: https://www.booking.com/hotel/no/gjestehuset102.en-gb.html?aid=361723;sid=806f4418ab60361a0493c13a7b90415a;dcid=4;checkin=2016-01-18;checkout=2016-01-22;dist=0;group_adults=2;room1=A%2CA;sb_price_type=total;srfid=cbb0f35bcd3b61a7d49f75713b3e8d78a9bc65a9X6;type=total;ucfs=1

Same hotel but much cheaper. Looking forward to it :snowflake: :bear:

**Comment by dcposch** [comment]
Will book a place later today. This Airbnb looks sweet: https://www.airbnb.com/rooms/6332769

"Wake up to the sound of the arctic ocean waves, or the ice churning against the frozen sea wall [...] breakfast included."

Would have space for one more. LMK if you're down to room together!

**Comment by dcposch** [comment]
Booked at the "Coal Miners' Cabins".

I'm also staying in Oslo afterward from the 22nd to the 25th. LMK if you want to go adventuring there!

**Comment by hackergrrl** [comment]
Hey @dcposch! Do you have a place lined up already? I'm going to be in Oslo from ~4pm on the 22nd to 6am on the 23rd. Adventuring could happen, and I would :heart: a couch to crash on.

**Comment by RichardLitt** [comment]
same :)
