### ISSUE TITLE
do we know who is speaking yet?

### ISSUE THREAD

**Issue by iancrowther** [adventure-js/arcticjs.club#6]
Is there even a plan to announce speaker or is this more an "un-conference" format?

**Comment by watson** [comment]
@iancrowther everyone attending are encouraged to speak :smiley: I know for sure that @feross, @mafintosh and my self are speaking. @jhiesey and @diasdavid might be speaking as well?

But in general expect a high level of audience participation, open discussions, informal workshops and co-hacking.

**Comment by iancrowther** [comment]
ok cool so the latter..
