### ISSUE TITLE
Ski trip?

### ISSUE THREAD

**Issue by RichardLitt** [adventure-js/arcticjs.club#7]
A friend of mine in Trondheim suggested we go on a skip trip, or a short trip.

> Here is the one: http://www.poliarctici.com/
> I've done a 3 days 2 nights cross country skiing tour. I had my own
> gear apart from the tent and sleeping bag.
> The guides and the tour were awesome, Id only recommend to check the
> sleeping bag. We got -27 and the one I got from the was not warm
> enough. Probably some rein deer skin in between the bag and the mat
> would do it, so check with them if they have such option in case it is
> too cold.

There's nothing offered in January, but maybe we can contact them and ask about a half-day trip or something.

**Comment by watson** [comment]
I'm not sure if it's possible because of the darkness? But I'll leave that decision up the the guides. I don't have any of the gear necessary though.

**Comment by RichardLitt** [comment]
They should have some of it. But yeah! Maybe? I have subzero camping gear, debating bringing it.

**Comment by despairblue** [comment]
How about a [dog sled expedition](http://www.svalbardvillmarkssenter.no/portfolio_item/heldags-hundeslede-ekspedisjon/?lang=en) or a [cave trip under a glacier](http://www.svalbardvillmarkssenter.no/portfolio_item/isgrotte-under-isbreen/?lang=en) or [Arctic dog sled expedition in the polar night](http://www.svalbardhusky.no/booking.html#arctic_dogsled)?

**Comment by RichardLitt** [comment]
Definitely the dog sled and the cave trip. Both, if possible.

**Comment by feross** [comment]
Our Airbnb host has a company that organizes arctic adventures for small groups. He sent me this:

> We can offer you two trips at this time.
> 
> An icecave trip With scootertransport at 650,-nok/person (approx. 4 hours with snacks and drinks) and a scootertrip at 1600,-nok/person (4-5 hours With lunch). There will be good chances of seeing aurora on both trips if it's Clear sky.
> 
> I can also recommend a dogsledgetrip full 2000,-/person or half day 1290,-/person.

Thoughts?

**Comment by RichardLitt** [comment]
Icecave. Thursday. Let's go! Where do I sign up?

**Comment by fbaiodias** [comment]
I'm in for that as well!

**Comment by feross** [comment]
Okay, I just confirmed with the host that we're all in for the ice cave trip on snow scooters.

I'm hoping that we're talking more like:

https://www.google.com/search?q=scootertransport&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiizeG_27bKAhWn73IKHYg2AWIQ_AUICCgC&biw=1276&bih=728#tbm=isch&q=sneeuwscooter

and not

https://www.google.com/search?q=scootertransport&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiizeG_27bKAhWn73IKHYg2AWIQ_AUICCgC&biw=1276&bih=728#tbm=isch&q=snow+scooter&imgrc=eXp2XECAzseAYM%3A

**Comment by feross** [comment]
If you're not down to go, let me know.

**Comment by watson** [comment]
:+1: from me :smiley:

**Comment by despairblue** [comment]
icecave me :+1: Jasmin :+1:

**Comment by whyrusleeping** [comment]
:+1:

**Comment by feross** [comment]
Just got this update from Jens:

> Hi, the cave is not open yet and we have decided to open it next week. Then there is only the icecave you walk to for 1 1/2 hour up about 500 meters or a short skidootrip 3-4 hours out in the valley I can go down to 1000,-/person with two on each scooter.

So, it sounds like we can do the closer ice cave for the same price (650 NOK), or take the snowmobiles out into the valley for 1000 NOK.
