### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by RichardLitt** [adventure-js/arcticjs.club#9]
We should have a list of speakers and their topics. Currently, I know that @feross, @mafintosh, @watson all want to walk. I'd like to, too. 

Proposal: If you would like to talk, throw your hat in the ring below. If possible, include short abstracts about what you are going to talk about.

**Comment by mafintosh** [comment]
@RichardLitt sounds good

@feross and i were discussing doing a joint security talk about node since we've unraveling a bunch of node security related issues lately
